services:
    php:
        container_name: tall-setup-php
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        restart: unless-stopped
        tty: true
        volumes:
            - .:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./storage/app/public:/var/www/storage/app/public
        networks:
            - tall-network
        depends_on:
            - mysql
#            - redis

    nginx:
        container_name: tall-setup-nginx
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        restart: unless-stopped
        tty: true
        ports:
            - '8000:80'
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - tall-network
        depends_on:
            - php

    mysql:
        container_name: tall-setup-mysql
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        tty: true
        volumes:
            - setup-data:/var/lib/mysql/
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - tall-network
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: tall_project
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: 123456

    phpmyadmin:
        container_name: tall-setup-phpmyadmin
        image: phpmyadmin:5.2
        restart: always
        ports:
            - '8888:80'
        environment:
            PMA_HOST: tall-setup-mysql
        networks:
            - tall-network
        depends_on:
            - mysql

networks:
    tall-network:
        driver: bridge

volumes:
    setup-data:
        driver: local
