services:
    php:
        container_name: tall-setup-php
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        restart: unless-stopped
        tty: true
        volumes:
            - .:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./storage/app/public:/var/www/storage/app/public
        networks:
            - tall-network
        depends_on:
            - mysql
#            - redis

    nginx:
        container_name: tall-setup-nginx
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        restart: unless-stopped
        tty: true
        ports:
            - '8000:80'
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - tall-network
        depends_on:
            - php

    mysql:
        container_name: tall-setup-mysql
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        tty: true
        volumes:
            - setup-data:/var/lib/mysql/
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - tall-network
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: tall_project
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: 123456

    phpmyadmin:
        container_name: tall-setup-phpmyadmin
        image: phpmyadmin:5.2
        restart: always
        ports:
            - '8888:80'
        environment:
            PMA_HOST: tall-setup-mysql
        networks:
            - tall-network
        depends_on:
            - mysql

#    redis:
#        container_name: tall-setup-redis
#        image: redis:latest
#        restart: always
#        ports:
#            - '6381:6379'
#        networks:
#            - tall-network
#
#    worker:
#        container_name: tall-setup-worker
#        build:
#            context: ./docker/php
#            dockerfile: Dockerfile
#        restart: unless-stopped
#        volumes:
#            - .:/var/www
#        command: php artisan queue:work
#        networks:
#            - tall-network
#        depends_on:
#            - redis
#
#    pest:
#        container_name: tall-setup-pest
#        build:
#            context: ./docker/php
#            dockerfile: Dockerfile
#        volumes:
#            - .:/var/www
#        working_dir: /var/www
#        command: ./vendor/bin/pest
#        networks:
#            - tall-network
#        depends_on:
#            - mysql
#            - redis

networks:
    tall-network:
        driver: bridge

volumes:
    setup-data:
        driver: local
